# ----
# Site

title: Foto Costiui.Net
url: "https://foto.costiui.net"
baseurl: "https://foto.costiui.net"
google_analytics_key: "UA-147213854-2"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "Foto Costiui.Net Fotogafi Costiui."
author: "Costiui"
  name: "Costiui Ronaszek"
  email:
  twitter: "costiui"
social:
  name: "Foto Costiui.Net"
  links: "https://github.com/Costiui/foto.costiui.net"

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /images/_screenshot.png
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
